# Generated by Django 6.1.1 on 2026-09-25 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('achat', 'Achat'), ('remboursement', 'Remboursement')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reference_mobile_money', models.CharField(max_length=100, unique=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('reussi', 'Réussi'), ('echec', 'Echec')], default='en_cours', max_length=20)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='games.ticker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
