# Generated by Django 6.1.1 on 2026-09-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_mobile_money',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
