# Generated by Django 6.1.1 on 2026-09-25 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('payments', '0002_alter_transaction_reference_mobile_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='partie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='games.partie'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='quantite_tickets',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
