# Generated by Django 6.0.8 on 2026-09-30 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_ticker_partie_remove_ticker_user_and_more'),
        ('payments', '0003_transaction_partie_transaction_quantite_tickets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date_transaction',
            new_name='date_creation',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ticker',
        ),
        migrations.AddField(
            model_name='transaction',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='games.ticket'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='partie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='games.partie'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('reussie', 'Réussie'), ('echouee', 'Échouée')], default='en_attente', max_length=20),
        ),
    ]
