# Generated by Django 6.0.8 on 2026-09-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_nomber',
            new_name='phone_number',
        ),
    ]
