# Generated by Django 6.0.8 on 2026-09-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeaide',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('fin_partie', 'Fin de partie'), ('resultat', 'Résultat / gagnant'), ('remboursement', 'Remboursement'), ('aide', 'Aide communautaire')], max_length=20),
        ),
    ]
