# Generated by Django 6.1.1 on 2026-09-25 12:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='parties/')),
                ('prix_produit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_ticket', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('montant_collecte', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('reussi', 'Réussi'), ('annule', 'Annulé')], default='en_cours', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('statut', models.CharField(choices=[('valide', 'Valide'), ('gagnant', 'Gagnant'), ('rembourse', 'Remboursé')], default='valide', max_length=20)),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickers', to='games.partie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='partie',
            name='ticker_gagnant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='games.ticker'),
        ),
    ]
