# Generated by Django 6.0.8 on 2026-09-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partie',
            name='notification_finale_envoyee',
            field=models.BooleanField(default=False),
        ),
    ]
