# Generated by Django 6.0.8 on 2026-09-30 02:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_partie_notification_finale_envoyee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='partie',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='user',
        ),
        migrations.RemoveField(
            model_name='partie',
            name='ticker_gagnant',
        ),
        migrations.AlterField(
            model_name='partie',
            name='prix_ticket',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='partie',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('reussie', 'Réussie'), ('annulee', 'Annulée')], default='en_cours', max_length=20),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='games.partie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='partie',
            name='ticket_gagnant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='games.ticket'),
        ),
    ]
