# Generated by Django 6.0.8 on 2026-09-30 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_ticker_partie_remove_ticker_user_and_more'),
        ('payments', '0004_rename_date_transaction_transaction_date_creation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticker',
        ),
    ]
