# Generated by Django 6.0.8 on 2026-09-30 03:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_delete_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date_achat',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 30, 3, 1, 31, 972178, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='statut',
            field=models.CharField(choices=[('valide', 'Valide'), ('gagnant', 'Gagnant'), ('rembourse', 'Remboursé')], default='valide', max_length=20),
        ),
    ]
